server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: BILLING-SERVICE
          uri: lb://BILLING-SERVICE
          predicates:
            - Path=/billing/**
        - id: PASSENGER-SERVICE
          uri: lb://PASSENGER-SERVICE
          predicates:
            - Path=/passenger/**
    config.enabled: false


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
